### ISSUE TITLE
The all_filters filter doesn't seem to be working

### ISSUE THREAD

**Issue by prurigro** [MiSTer-devel/Distribution_MiSTer#29]
Hi, first I should say thank you for the continued hard work on this!

I wanted to remove `other-cores` while keeping everything else update_all normally pulls in, so I added the following to my `downloader.ini`:

```
[mister]
filter = all_filters !other_cores
```

I assumed `all_filters` would result in a starting point with all filters applied which I could then negate from, but running `update_all.sh` proceeded to delete absolutely everything.

There's currently no description for `all_filters` so I might be misunderstanding its use case, but it also didn't appear to pull anything in. Either way, it would be great to have the full set of files as a starting point to then negate individual filters from.

Thanks!

**Comment by theypsilon** [comment]
Hey @prurigro , there is actually some description for `all_filters` in the README of this repository:

<img width="681" alt="image" src="https://user-images.githubusercontent.com/852246/152029780-e74e88d9-3aea-4dec-b029-9f24f4d7c452.png">

The filter you wanted to use is `all`. I didn't document that one because is really not necessary to use. When you use a negated filter, and no other non-negated filters, there always be a implicit `all` filter being applied. Otherwise you could not negate from an empty set, as you correctly guessed.

As a fun fact, if you use `!all`, you will delete ALL files from the database. Not very useful though!

**Comment by prurigro** [comment]
You're right, I definitely missed that when parsing (probably should have done a search!). Assuming I didn't also skim past mention of the implicit all, it might be worth mentioning that in the readme?

Thanks for the info and again for all your hard work!
